# Generated by Django 4.2.4 on 2023-09-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_delete_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='photo',
        ),
    ]
