# Generated by Django 4.2.4 on 2023-09-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
